### ISSUE TITLE
Unknown option error on start up

### ISSUE THREAD

**Issue by jsatk** [dag/vim-fish#36]
![screen shot 2016-10-18 at 9 56 47 am](https://cloud.githubusercontent.com/assets/1005550/19487988/d26a31f0-9519-11e6-88d8-b0c3b90e2f9a.png)

Any time I view a `.fish` file I get this warning. This is new. I've used this plugin for years. 

The syntax highlighting still totally works. 

Any ideas?

**Comment by oschrenk** [comment]
Seems like an issue with whitespace in the path to your bundles. 

Between Dropbox and (Personal) . Escape it or get rid.

**Comment by jsatk** [comment]
Thank you! This is exactly it.
