### ISSUE TITLE
Not keyword is not highlighted

### ISSUE THREAD

**Issue by karlek** [dag/vim-fish#39]
dag/vim-fish
![out5958](https://cloud.githubusercontent.com/assets/1278705/21840891/3249c0f0-d7e0-11e6-98fb-58ee41b04afe.png)

`fish, version 2.4.0`
![out9659](https://cloud.githubusercontent.com/assets/1278705/21840912/4d7a7eaa-d7e0-11e6-9ccb-9a9697949bcf.png)

**Comment by karlek** [comment]
It looks like the fix is to add `not` to `fishConditional` here: https://github.com/dag/vim-fish/blob/825853f4816a07e59ea2ecee1190ab6a5d9ef991/syntax/fish.vim

**Comment by dag** [comment]
No, you'd have to put it in `fishLineContinuation`, which would mean it gets highlighted everywhere, as an argument to any command. Note that `not` gets highlighted correctly if it's on its own; problem is `if` works like `sudo` and other such commands that wrap other commands. Thus, `not` is technically just a string argument to `if` and it's technically correct not to highlight it as anything other than a string argument. You could make a special syntax rule for `if` but that gets hairy fast with Vim syntax rules, and tends to be slow. I decided against that for vim-fish.

**Comment by dag** [comment]
The other way to do it is to drop `fishLineContinuation` all-together and just make things like `not` keywords. But then a line like `echo if begin function end` highlights like a bunch of keywords, even though only `echo` was anything other than a string argument. I decided it was more helpful to ensure that nothing is incorrectly highlighted as a keyword, than to ensure that anything that possibly ever could be a keyword always gets highlighted as such.

**Comment by karlek** [comment]
Good conclusion. It's better to not highlight keywords incorrectly.
